# pull official base image
FROM python:3.10-bullseye

# set default interpreter as bash
RUN chsh -s /bin/bash

# set work directory
WORKDIR /testdb

ADD . /testdb

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


RUN apt-get update -y && apt-get upgrade -y

# Preparing dependencies
RUN apt-get install -y \
    libgdal-dev libpq-dev libxml2-dev \
    libxml2 libxslt1-dev zlib1g-dev libjpeg-dev \
    libmemcached-dev libldap2-dev libsasl2-dev libffi-dev

RUN apt-get install -y --no-install-recommends \
    gcc zip \
    python3-all-dev python3-dev \
    python3-gdal

# install python dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt