# Generated by Django 4.1.6 on 2023-03-21 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='created on')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='modified on')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='File name')),
                ('mime_type', models.CharField(max_length=255, verbose_name='MIME Type of file')),
                ('file_metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata of the file')),
                ('file', models.FileField(upload_to='file_uploads/')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'Files',
            },
        ),
    ]
